[build]
  command = "npm install prisma@6.6.0 && npx prisma generate && next build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_RUNTIME = "netlify"
  NEXT_PUBLIC_CONTACT_EMAIL = "ascensionpremium@gmail.com"
  PRISMA_GENERATE_IN_POSTBUILD = "true"
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-1.0.x,debian-openssl-3.0.x"
  # Não é necessário configurar variáveis de ambiente no painel do Netlify
  # pois estamos usando o arquivo .env.local

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "next"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**", "node_modules/.prisma/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuração para garantir que rotas de API funcionem corretamente
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Configuração para garantir que as rotas do Next.js funcionem corretamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=3600"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:;"

# Comandos de lifecycle para o Prisma
[build.lifecycle]
  preBuild = "npx prisma generate" 