[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PRISMA_GENERATE_IN_POSTBUILD = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Regras de redirecionamento para APIs
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

# Regra para imagens
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

# Regra para rotas de páginas  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 